version: '2.0'
services:
  proxy:
    image: nginx
    volumes: 
      - ./frnd.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "8080:80"
    command:
      - nginx
      - "-g"
      - "daemon off;"
