version: '3.7'
services:
  web:
    container_name: frnd_web
    build:
      context: client
      target: prod
    volumes:
      - ./client/nginx.conf.template:/etc/nginx/templates/default.conf.template
    ports: 
      - "8080:80"
    environment:
      - SVC_HOST
      - SVC_PORT
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - service
    networks:
      - web
      - svc
  service:
    container_name: frnd_svc
    build:
      context: server
    volumes:
      - ./server:/app
    environment:
      - PORT=${SVC_PORT}
      - LOG_LEVEL=${SVC_LOG_LEVEL}
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DB_TIMEOOUT
      - APP_SECRET
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - svc
      - db
  database:
    container_name: frnd_db
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    networks:
      - db

volumes:
  mongodata:

networks:
  web: {}
  svc: {}
  db: {}
