// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	models "github.com/chakradeb/frnd-server/models"
	mock "github.com/stretchr/testify/mock"
)

// IDBClient is an autogenerated mock type for the IDBClient type
type IDBClient struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: _a0, _a1
func (_m *IDBClient) CreateUser(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: _a0
func (_m *IDBClient) GetUser(_a0 string) (*models.User, error) {
	ret := _m.Called(_a0)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
