// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IDBClient is an autogenerated mock type for the IDBClient type
type IDBClient struct {
	mock.Mock
}

// CheckUserAlreadyExists provides a mock function with given fields: _a0
func (_m *IDBClient) CheckUserAlreadyExists(_a0 string) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CreateUser provides a mock function with given fields: _a0, _a1
func (_m *IDBClient) CreateUser(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
